In [ ]:
import numpy as np

# (1). Create a 1D NumPy Array
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print("Week 1 Temperatures:", temperatures_w1)

# (2). Inspection and Properties
print("\n--- Inspection ---")
print(f"Shape: {temperatures_w1.shape}")
print(f"Data Type: {temperatures_w1.dtype}")
print(f"Number of elements: {temperatures_w1.size}")
print(f"Dimensions: {temperatures_w1.ndim}")

Week 1 Temperatures: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]

--- Inspection ---
Shape: (7,)
Data Type: float64
Number of elements: 7
Dimensions: 1


In [ ]:


# (3). Array Operations:

# Convert Celsius to Fahrenheit: Fahrenheit = (Celsius * 9/5) + 32
temperatures_f = (temperatures_w1 * 9/5) + 32
print("Temperatures in Fahrenheit:", temperatures_f)

# Find max, min, mean
max_temp = np.max(temperatures_w1)
min_temp = np.min(temperatures_w1)
mean_temp = np.mean(temperatures_w1)

print(f"Maximum Temperature: {max_temp}°C")
print(f"Minimum Temperature: {min_temp}°C")
print(f"Mean Temperature: {mean_temp:.2f}°C")

# (4). Array Slicing and Indexing:

# First three days of the week
first_three = temperatures_w1[:3]
print("\nFirst three days:", first_three)

# Weekend (last two days)
weekend = temperatures_w1[-2:]
print("Weekend (last two days):", weekend)

# Middle three days of the week (Day 3, 4, 5 -> index 2,3,4)
middle_three = temperatures_w1[2:5]
print("Middle three days:", middle_three)

Temperatures in Fahrenheit: [72.5  77.54 69.44 74.12 78.98 76.64 71.42]
Maximum Temperature: 26.1°C
Minimum Temperature: 20.8°C
Mean Temperature: 23.54°C

First three days: [22.5 25.3 20.8]
Weekend (last two days): [24.8 21.9]
Middle three days: [20.8 23.4 26.1]


In [ ]:


# (5). Create a 2D Array
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9], # Row 1: Week 1
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1] # Row 2: Week 2
])

print("2D Temperatures Array:\n", temperatures)

# (6). Inspect and Slice the 2D Array:

# Inspect properties
print("\n--- Inspection ---")
print(f"Shape: {temperatures.shape}") # (2, 7) -> 2 rows, 7 columns
print(f"Data Type: {temperatures.dtype}") # float64
print(f"Total elements: {temperatures.size}") # 14
print(f"Dimensions: {temperatures.ndim}") # 2

# Extract temperatures for each week
week1 = temperatures[0, :] # or temperatures[0]
week2 = temperatures[1, :] # or temperatures[1]

print("\nWeek 1:", week1)
print("Week 2:", week2)

# Extract weekends (last two days) for both weeks
# : means all rows, -2: means last two columns
weekends = temperatures[:, -2:]
print("\nWeekends for both weeks (last two days):\n", weekends)

# If you want separately:
print("Week 1 Weekend:", temperatures[0, -2:])
print("Week 2 Weekend:", temperatures[1, -2:])

2D Temperatures Array:
 [[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]

--- Inspection ---
Shape: (2, 7)
Data Type: float64
Total elements: 14
Dimensions: 2

Week 1: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2: [19.2 22.5 21.3 24.  23.5 22.8 20.1]

Weekends for both weeks (last two days):
 [[24.8 21.9]
 [22.8 20.1]]
Week 1 Weekend: [24.8 21.9]
Week 2 Weekend: [22.8 20.1]


In [ ]:
import pandas as pd

# (1). Creating Pandas Series
marks = pd.Series(
    data=[95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)
print("Marks Series:\n", marks)

# (2). Indexing and Slicing:

# Use integer index position to access the mark of the 1st rank student
# Rank1 is at position 0
print("\n1st rank mark (integer position [0]):", marks[0])

# Use loc accessor to retrieve marks of top 3 ranks by specifying index labels
top_3 = marks.loc[['Rank1', 'Rank2', 'Rank3']]
# Or you can use slicing with loc: marks.loc['Rank1':'Rank3']
print("\nTop 3 ranks using loc:\n", top_3)

# Use iloc accessor to retrieve the mark of the 3rd rank student
# 3rd rank is at iloc position 2
third_rank = marks.iloc[2]
print("\n3rd rank mark using iloc[2]:", third_rank)

# Apply boolean mask to filter Series where marks > 90
greater_than_90 = marks[marks > 90]
print("\nRanks where marks > 90:\n", greater_than_90)

Marks Series:
 Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

1st rank mark (integer position [0]): 95

Top 3 ranks using loc:
 Rank1    95
Rank2    92
Rank3    89
dtype: int64

3rd rank mark using iloc[2]: 89

Ranks where marks > 90:
 Rank1    95
Rank2    92
dtype: int64


/tmp/ipykernel_864/2914893950.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("\n1st rank mark (integer position [0]):", marks[0])


In [ ]:
# (3). Manipulating Series

# 1. Modify the mark of the student with 1st rank to 100
marks['Rank1'] = 100
# OR: marks.loc['Rank1'] = 100
print("After modifying Rank1 to 100:\n", marks)

# (2). Remove the entry corresponding to the last rank from the Series
# Last rank is 'Rank5'
marks = marks.drop('Rank5')
print("\nAfter removing last rank (Rank5):\n", marks)

# (3). Compute the CGPA by dividing each mark in the Series by 10
cgpa = marks / 10
print("\nCGPA (Marks / 10):\n", cgpa)

After modifying Rank1 to 100:
 Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

After removing last rank (Rank5):
 Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

CGPA (Marks / 10):
 Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


In [ ]:
import pandas as pd

# (1). Creating Pandas DataFrame named transactions
transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture',
                        'Clothing', 'Electronics', 'Furniture', 'Clothing',
                        'Furniture', 'Electronics'],
    'Region': ['North', 'South', 'North', 'East', 'West',
               'North', 'East', 'West', 'South', 'North'],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [ ]:
# (2). DATA EXPLORATION

# (1). Display DataFrame and basic info
print("Full DataFrame:\n", transactions)
print("\nHead (first 5):\n", transactions.head())
print("\nTail (last 5):\n", transactions.tail())
print("\nShape:", transactions.shape) # (10, 4)
print("\nColumn Names:", transactions.columns.tolist())
print("\nData Types:\n", transactions.dtypes)
print("\nInfo:")
print(transactions.info())
print("\nDescribe:\n", transactions.describe())

# (2). Display only 'ProductCategory' and 'Amount' columns
print("\n--- ProductCategory and Amount ---\n", transactions[['ProductCategory', 'Amount']])

# (3). Retrieve the last 3 columns using iloc or loc
# iloc -> last 3 columns are index 1,2,3
print("\n--- Last 3 columns (iloc) ---\n", transactions.iloc[:, -3:])
# loc -> by column names
print("\n--- Last 3 columns (loc) ---\n", transactions.loc[:, 'ProductCategory':'Amount'])

# (4). Filter rows where Region is 'North' and Amount > 200
filtered = transactions[(transactions['Region'] == 'North') & (transactions['Amount'] > 200)]
print("\n--- Region North and Amount > 200 ---\n", filtered)

# (5). Value counts for ProductCategory
print("\n--- Value counts for ProductCategory ---\n", transactions['ProductCategory'].value_counts())

# (6). Unique values in Region column
print("\n--- Unique Regions ---\n", transactions['Region'].unique())

# (7). Group by Region and find mean amount for each region
region_mean = transactions.groupby('Region')['Amount'].mean()
print("\n--- Mean Amount per Region ---\n", region_mean)

Full DataFrame:
    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

Head (first 5):
    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

Tail (last 5):
    TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   E

In [ ]:
# (3). MANIPULATING THE DATAFRAME

# (1). Modify the 'Amount' for the transaction with TransactionID 102 to 165
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165
print("After modifying Amount for ID 102:\n", transactions)

# (2). Add a new column 'Discount' by calculating 10% of the 'Amount'
transactions['Discount'] = transactions['Amount'] * 0.10
# OR: transactions['Discount'] = transactions['Amount'] * 10 / 100
print("\nAfter adding Discount column:\n", transactions)

# (3). Remove the row with TransactionID 109
transactions = transactions[transactions['TransactionID'] != 109]
# OR: transactions = transactions.drop(transactions[transactions['TransactionID'] == 109].index)
print("\nAfter removing row with ID 109:\n", transactions)

# (4). Delete the 'Discount' column from the DataFrame
transactions = transactions.drop(columns=['Discount'])
# OR: del transactions['Discount']
print("\nAfter deleting Discount column:\n", transactions)

After modifying Amount for ID 102:
    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

After adding Discount column:
    TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.